sonar.projectKey=oficina-app-pagamento
sonar.projectName=oficina-app-pagamento
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
